import './index.css'
const Partners =()=>{
    return(
        <div className='mainimages'>
           <h1>Partnership</h1> 
           <div className='images'>
            <img src='/media/Rotary.jpg' alt='rotary' className='rotary'/>
            <img src='/media/karen.png' alt='karen' className='karen'/>
            <img src='/media/page.png' alt='page' className='page'/>
           </div>
           <div className='matheew'></div>
           <p>We also partner with Mathew 25 Children's Home.The average cost to support one child is $4 per day.How we help them is bey providing them with fitting clothes and bedding.We also provide funds generated by resuing and recyling used textiles.The funds are used to strengthen and grow this home.</p>

        </div>
    )
}
export default Partners
